"""Shell function generation for wt."""

BASH_FUNCTIONS = """
# wt - Git worktree workflow tool
# Generated by: wt init bash

wt() {
  local result
  result=$(command wt "$@")
  local exit_code=$?

  if [ $exit_code -eq 0 ] && [ -d "$result" ]; then
    cd "$result" || return 1
  else
    echo "$result"
  fi

  return $exit_code
}

# Standalone command variants
wt-new() { wt new "$@"; }
wt-switch() { wt switch "$@"; }
wt-sw() { wt sw "$@"; }
wt-home() { wt home "$@"; }
wt-list() { wt list "$@"; }
wt-ls() { wt ls "$@"; }
wt-clean() { wt clean "$@"; }
wt-remove() { wt remove "$@"; }
"""

ZSH_FUNCTIONS = """
# wt - Git worktree workflow tool
# Generated by: wt init zsh

wt() {
  local result
  result=$(command wt "$@")
  local exit_code=$?

  if [[ $exit_code -eq 0 ]] && [[ -d "$result" ]]; then
    cd "$result" || return 1
  else
    echo "$result"
  fi

  return $exit_code
}

# Standalone command variants
wt-new() { wt new "$@"; }
wt-switch() { wt switch "$@"; }
wt-sw() { wt sw "$@"; }
wt-home() { wt home "$@"; }
wt-list() { wt list "$@"; }
wt-ls() { wt ls "$@"; }
wt-clean() { wt clean "$@"; }
wt-remove() { wt remove "$@"; }
"""


def get_shell_functions(shell: str) -> str:
    """Get shell functions for the specified shell.

    Args:
        shell: Shell type ("bash" or "zsh")

    Returns:
        Shell function code

    Raises:
        ValueError: If shell is not supported
    """
    if shell == "bash":
        return BASH_FUNCTIONS
    elif shell == "zsh":
        return ZSH_FUNCTIONS
    else:
        raise ValueError(f"Unsupported shell: {shell}. Must be 'bash' or 'zsh'")
